export const departamentos = [
  {
    dep: "Amazonas",
    muni: ["Leticia", "Mitú", "Alto Orinoco"],
  },
  {
    dep: "Antioquia",
    muni: ["Medellín", "Argelia", "Betulia", "Envigado"],
  },
  {
    dep: "Arauca",
    muni: ["Arauca", "Arauquita", "Fortul", "Tame"],
  },
  {
    dep: "Atlantico",
    muni: [
      "Barranquilla",
      "Caracolí",
      "Puerto Colombia",
      "Sabanagrande",
      "Soledad",
    ],
  },
  {
    dep: "Bogotá",
    muni: [
      "Antonio Nariño",
      "Usaquen",
      "Bosa",
      "Suba",
      "Engativa",
      "Kennedy",
      "Chapinero",
    ],
  },
  /* "Bolivar",
  "Boyaca",
  "Caldas",
  "Caqueta",
  "Casanare",
  "Cauca",
  "Cesar",
  "Choco",
  "Cordoba",
  "Cundinamarca",
  "Guainia",
  "Guajira",
  "Guaviare",
  "Huila",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindio",
  "Risaralda",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca", */
];
